### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getShortHead' of null

### ISSUE THREAD

**Issue by nallie** [atom/open-on-github#36]
[Enter steps to reproduce below:]

1... Trying to get my tree view to update the git status. So , opened it on git hub and receive this error.
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [open-on-github](https://github.com/atom/open-on-github) package, v0.32.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getShortHead' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/github-file.js:175

TypeError: Cannot read property 'getShortHead' of null
  at GitHubFile.module.exports.GitHubFile.remoteName (/Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/github-file.js:175:30)
  at GitHubFile.module.exports.GitHubFile.gitUrl (/Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/github-file.js:135:40)
  at GitHubFile.module.exports.GitHubFile.validationErrors (/Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/github-file.js:81:17)
  at GitHubFile.module.exports.GitHubFile.isOpenable (/Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/github-file.js:77:19)
  at GitHubFile.module.exports.GitHubFile.history (/Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/github-file.js:37:16)
  at atom-pane.atom.commands.add.open-on-github:history (/Applications/Atom.app/Contents/Resources/app/node_modules/open-on-github/lib/main.js:33:50)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
  5x -4:32.1 fuzzy-finder:toggle-git-status-finder (input.hidden-input)
  2x -2:37.7 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:27.4 dragstart (li.tab.sortable)
  3x -0:27.3 dragover (div.close-icon)
     -0:27.3 dragleave (div.close-icon)
     -0:27.1 dragend (li.tab.sortable)
     -0:00.6 open-on-github:history (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "autocomplete",
      "package-generator",
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.5.3
autoclose-html, v0.15.0
autocomplete-plus, v2.2.0
color-picker, v1.4.4
editorconfig, v0.3.0
emmet, v2.3.3
file-icons, v1.4.11
highlight-selected, v0.9.0
language-stylus, v0.1.0
linter, v0.12.0
minimap, v4.3.1
monokai, v0.12.0
sublime-tabs, v0.4.9

# Dev
No dev packages
```

**Comment by nallie** [comment]
It is working now. Random occurrence, cannot replicate this. Sorry about that.

**Comment by kevinsawicki** [comment]
I'm reopening, that stack trace definitely looks like a bug that should be fixed, even if it isn't consistently happening.
